# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'history' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for history
	pod 'IQKeyboardManagerSwift'
	pod 'Kingfisher', '~> 7.0'
  pod 'R.swift'
  pod 'Material', '~> 3.1.0'

  target 'historyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'historyUITests' do
    # Pods for testing
  end

end
